# Generated by Django 4.2.1 on 2023-07-28 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.ImageField(upload_to='assets/models/iconos/', verbose_name='icono')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'NavBar',
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Video', 'Video'), ('Accordeon', 'Accordeon'), ('Cuadros', 'Cuadros'), ('Contacto', 'Contacto'), ('Recomendaciones', 'Recomendaciones')], max_length=100, unique=True, verbose_name='Nombre de sección')),
                ('titulo', models.CharField(max_length=200, verbose_name='Texto principal')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('subtitulo', models.TextField(verbose_name='Subtítulo')),
                ('texto', models.TextField(verbose_name='Texto del slide')),
                ('boton_1', models.CharField(max_length=50, verbose_name='Botón 1')),
                ('boton_2', models.CharField(max_length=50, verbose_name='Botón 2')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Slide',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='assets/models/videos/')),
                ('thumbnail', models.ImageField(upload_to='assets/models/thumbnails/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('seccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secciones')),
            ],
        ),
        migrations.CreateModel(
            name='ElementosNavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200, verbose_name='Texto principal')),
                ('is_button', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, help_text='Si es butón agrega link externo, si es sección agrega el id de la sección.', max_length=100, verbose_name='Link')),
                ('orden', models.IntegerField(verbose_name='Orden en navbar')),
                ('seccion_id', models.CharField(blank=True, choices=[('inicio', 'inicio'), ('proceso', 'proceso'), ('contacto', 'contacto')], max_length=100, verbose_name='Nombre de sección')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('navbar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.navbar')),
            ],
            options={
                'verbose_name_plural': 'ElementosNavBar',
            },
        ),
        migrations.CreateModel(
            name='CuadrosItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cuadro')),
                ('texto', models.TextField()),
                ('icono', models.ImageField(upload_to='assets/models/iconos/', verbose_name='icono')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('seccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secciones')),
            ],
            options={
                'verbose_name_plural': 'Cuadros Items',
            },
        ),
        migrations.CreateModel(
            name='ContactoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(blank=True)),
                ('icono', models.ImageField(upload_to='assets/models/iconos/', verbose_name='icono')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('seccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secciones')),
            ],
            options={
                'verbose_name_plural': 'Contacto Items',
            },
        ),
        migrations.CreateModel(
            name='AccordeonsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del accordeon')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('icono', models.ImageField(upload_to='assets/models/iconos/', verbose_name='icono')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('seccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secciones')),
            ],
            options={
                'verbose_name_plural': 'Accordeons Items',
            },
        ),
    ]
