# Generated by Django 4.2.1 on 2023-07-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_elementosnavbar_seccion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='elementosnavbar',
            name='is_button',
            field=models.BooleanField(default=False, verbose_name='¿Es botón?'),
        ),
    ]
