# Generated by Django 4.2.1 on 2023-07-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_secciones_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoitems',
            name='link',
            field=models.CharField(blank=True, help_text='Si es necesario enviar a otro sitio como Google Maps.', max_length=100, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='contactoitems',
            name='order_id',
            field=models.IntegerField(default=0, verbose_name='Orden en sección'),
        ),
    ]
