# Generated by Django 4.2.1 on 2023-08-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactoitems_link_contactoitems_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoitems',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='¿Es requerido?'),
        ),
        migrations.AddField(
            model_name='contactoitems',
            name='placeholder',
            field=models.CharField(blank=True, max_length=100, verbose_name='Placeholder'),
        ),
    ]
