# Generated by Django 4.2.1 on 2023-08-01 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactoitems_is_required_contactoitems_placeholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoitems',
            old_name='order_id',
            new_name='order',
        ),
    ]
